### ISSUE TITLE
Track bar

### ISSUE THREAD

**Issue by NejiWashed** [MrFacysus/VoVRant#3]
hey, which code do i need to put the SizeX
and sizeY into a trackbar to make it shoot better

btw sry for my bad english 
![1](https://user-images.githubusercontent.com/108196938/175796203-05a3b979-1979-4b5c-a176-52e86cd65c5c.PNG)
![2](https://user-images.githubusercontent.com/108196938/175796205-5a4f2db3-5365-4788-bec3-cf0e7a8bdfd1.PNG)

**Comment by MrFacysus** [comment]
SizeX & SizeY are integers which represent how much from the center of the screen is taken!

**Comment by MrFacysus** [comment]
To make it shoot better lower the values, ultimately but, your main idea should be to still have them kind of high to get it detecting both sides of the head!

**Comment by NejiWashed** [comment]
so i need to edit this value to get both sides of the head?
![this](https://user-images.githubusercontent.com/108196938/175812237-426b8b72-503e-4f74-bf9c-55fdc8fbe24d.PNG)

**Comment by MrFacysus** [comment]
I don't think you need to edit that. That is a method where it wants to find pixels of the same color from both sides of the screen but if you don't like that method you can change it to your liking. If not just change sizeX and sizeY to lower
