### ISSUE TITLE
somethings wrong

### ISSUE THREAD

**Issue by Scharpex** [MrFacysus/VoVRant#5]
i copied code and i bind K in game settings to shoot,but it doesnt work Is there anything I need to add to the code?

**Comment by MrFacysus** [comment]
If you are playing on primary monitor, if it's 1920x1080, if your k is really binded to firing and if they didn't find a way to detect it, you should be fine. But I got a few people saying they got banned, so I'd watch out!

**Comment by Scharpex** [comment]
i found the problem how can i make it stable for 1366x768
